// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traveler_Compass.Data;

#nullable disable

namespace Traveler_Compass.Migrations
{
    [DbContext(typeof(CompassDbContext))]
    [Migration("20230705214929_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Agent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Itinerary", b =>
                {
                    b.Property<int>("itineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itineraryId"));

                    b.Property<int?>("Agentid")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("userId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("itineraryId");

                    b.HasIndex("Agentid");

                    b.HasIndex("userId1");

                    b.ToTable("itineraries");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Package", b =>
                {
                    b.Property<int>("packageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("packageId"));

                    b.Property<int>("agentId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itineraryId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("userId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("packageId");

                    b.HasIndex("agentId");

                    b.HasIndex("itineraryId");

                    b.HasIndex("userId1");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Itinerary", b =>
                {
                    b.HasOne("Traveler_Compass.Models.Domain.Agent", null)
                        .WithMany("itineraries")
                        .HasForeignKey("Agentid");

                    b.HasOne("Traveler_Compass.Models.Domain.User", "User")
                        .WithMany("itineraries")
                        .HasForeignKey("userId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Package", b =>
                {
                    b.HasOne("Traveler_Compass.Models.Domain.Agent", "agent")
                        .WithMany("packages")
                        .HasForeignKey("agentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traveler_Compass.Models.Domain.Itinerary", "itinerary")
                        .WithMany("packages")
                        .HasForeignKey("itineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traveler_Compass.Models.Domain.User", "user")
                        .WithMany("packages")
                        .HasForeignKey("userId1");

                    b.Navigation("agent");

                    b.Navigation("itinerary");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Agent", b =>
                {
                    b.Navigation("itineraries");

                    b.Navigation("packages");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.Itinerary", b =>
                {
                    b.Navigation("packages");
                });

            modelBuilder.Entity("Traveler_Compass.Models.Domain.User", b =>
                {
                    b.Navigation("itineraries");

                    b.Navigation("packages");
                });
#pragma warning restore 612, 618
        }
    }
}
